services:
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:8080"

  order-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:8080"

  media-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  postgres-identity:
    ports:
      - "5433:5432"

  postgres-catalog:
    ports:
      - "5434:5432"

  postgres-order:
    ports:
      - "5435:5432"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
